CREATE TABLE IF NOT EXISTS `carepay_hospital_booking` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `application_id` VARCHAR(64) NOT NULL,
  `lan` VARCHAR(64) NOT NULL,
  `hospital_legal_name` VARCHAR(255) NOT NULL,
  `brand_name` VARCHAR(255) DEFAULT NULL,
  `branch_locations` TEXT DEFAULT NULL,
  `hospital_registration_number` VARCHAR(128) DEFAULT NULL,
  `year_of_establishment` VARCHAR(16) DEFAULT NULL,
  `hospital_type` VARCHAR(100) DEFAULT NULL,
  `bed_capacity` INT DEFAULT NULL,
  `key_specialties` TEXT DEFAULT NULL,
  `major_procedures` TEXT DEFAULT NULL,
  `departments` TEXT DEFAULT NULL,
  `registered_address` TEXT NOT NULL,
  `registered_city` VARCHAR(100) NOT NULL,
  `registered_district` VARCHAR(100) NOT NULL,
  `registered_state` VARCHAR(100) NOT NULL,
  `registered_pincode` VARCHAR(12) NOT NULL,
  `hospital_email` VARCHAR(255) DEFAULT NULL,
  `hospital_phone` VARCHAR(20) NOT NULL,
  `contact_person_name` VARCHAR(150) NOT NULL,
  `contact_person_email` VARCHAR(255) DEFAULT NULL,
  `contact_person_phone` VARCHAR(20) NOT NULL,
  `ifsc_code` VARCHAR(20) NOT NULL,
  `bank_name` VARCHAR(150) NOT NULL,
  `branch_name` VARCHAR(150) NOT NULL,
  `account_holder_name` VARCHAR(255) NOT NULL,
  `account_number` VARCHAR(64) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_carepay_hospital_application_id` (`application_id`),
  UNIQUE KEY `uk_carepay_hospital_lan` (`lan`),
  KEY `idx_carepay_hospital_status_name` (`status`, `hospital_legal_name`),
  KEY `idx_carepay_hospital_city` (`registered_city`, `registered_district`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `loan_booking_carepay` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lan` VARCHAR(64) NOT NULL,
  `partner_loan_id` VARCHAR(100) NOT NULL,
  `login_date` DATE NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `middle_name` VARCHAR(100) DEFAULT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `customer_name` VARCHAR(255) NOT NULL,
  `gender` VARCHAR(20) NOT NULL,
  `dob` DATE NOT NULL,
  `age` INT DEFAULT NULL,
  `father_name` VARCHAR(150) DEFAULT NULL,
  `mother_name` VARCHAR(150) DEFAULT NULL,
  `mobile_number` VARCHAR(20) NOT NULL,
  `email_id` VARCHAR(255) DEFAULT NULL,
  `pan_number` VARCHAR(20) NOT NULL,
  `aadhar_number` VARCHAR(20) DEFAULT NULL,
  `current_address` TEXT NOT NULL,
  `current_village_city` VARCHAR(100) NOT NULL,
  `current_district` VARCHAR(100) NOT NULL,
  `current_state` VARCHAR(100) NOT NULL,
  `current_pincode` VARCHAR(12) NOT NULL,
  `permanent_address` TEXT DEFAULT NULL,
  `permanent_village_city` VARCHAR(100) DEFAULT NULL,
  `permanent_district` VARCHAR(100) DEFAULT NULL,
  `permanent_state` VARCHAR(100) DEFAULT NULL,
  `permanent_pincode` VARCHAR(12) DEFAULT NULL,
  `loan_amount` DECIMAL(15,2) NOT NULL,
  `interest_rate` DECIMAL(10,4) DEFAULT NULL,
  `roi_apr` DECIMAL(10,4) DEFAULT NULL,
  `loan_tenure` INT NOT NULL,
  `emi_amount` DECIMAL(15,2) DEFAULT NULL,
  `cibil_score` INT DEFAULT NULL,
  `product` VARCHAR(100) NOT NULL DEFAULT 'Medical Insurance',
  `lender` VARCHAR(100) NOT NULL DEFAULT 'CAREPAY',
  `loan_type` VARCHAR(100) NOT NULL DEFAULT 'Personal Loan',
  `bank_name` VARCHAR(150) DEFAULT NULL,
  `name_in_bank` VARCHAR(255) DEFAULT NULL,
  `account_number` VARCHAR(64) DEFAULT NULL,
  `ifsc` VARCHAR(20) DEFAULT NULL,
  `account_type` VARCHAR(50) DEFAULT NULL,
  `type_of_account` VARCHAR(50) DEFAULT NULL,
  `net_disbursement` DECIMAL(15,2) DEFAULT NULL,
  `employment` VARCHAR(100) DEFAULT NULL,
  `risk_category` VARCHAR(100) DEFAULT NULL,
  `customer_type` VARCHAR(100) DEFAULT NULL,
  `annual_income` DECIMAL(15,2) DEFAULT NULL,
  `hospital_id` BIGINT UNSIGNED NOT NULL,
  `hospital_lan` VARCHAR(64) DEFAULT NULL,
  `hospital_name` VARCHAR(255) NOT NULL,
  `hospital_bank_name` VARCHAR(150) DEFAULT NULL,
  `hospital_account_holder_name` VARCHAR(255) DEFAULT NULL,
  `hospital_account_number` VARCHAR(64) DEFAULT NULL,
  `hospital_ifsc` VARCHAR(20) DEFAULT NULL,
  `policy_type` VARCHAR(100) NOT NULL,
  `patient_name` VARCHAR(255) DEFAULT NULL,
  `insurance_company_name` VARCHAR(255) DEFAULT NULL,
  `insurance_policy_holder_name` VARCHAR(255) DEFAULT NULL,
  `insurance_policy_number` VARCHAR(100) DEFAULT NULL,
  `relation_with_policy_holder` VARCHAR(100) DEFAULT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'Login',
  `stage` VARCHAR(50) DEFAULT NULL,
  `agreement_date` DATE DEFAULT NULL,
  `bank_status` VARCHAR(50) DEFAULT NULL,
  `enach_umrn` VARCHAR(100) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_carepay_lan` (`lan`),
  UNIQUE KEY `uk_carepay_partner_loan_id` (`partner_loan_id`),
  KEY `idx_carepay_pan_status` (`pan_number`, `status`),
  KEY `idx_carepay_status_lan` (`status`, `lan`),
  KEY `idx_carepay_hospital` (`hospital_id`),
  CONSTRAINT `fk_carepay_hospital`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `carepay_hospital_booking` (`id`)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `manual_rps_carepay` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lan` VARCHAR(64) NOT NULL,
  `due_date` DATE NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'Due',
  `emi` DECIMAL(15,2) DEFAULT 0.00,
  `interest` DECIMAL(15,2) DEFAULT 0.00,
  `principal` DECIMAL(15,2) DEFAULT 0.00,
  `opening` DECIMAL(15,2) DEFAULT 0.00,
  `closing` DECIMAL(15,2) DEFAULT 0.00,
  `remaining_emi` DECIMAL(15,2) DEFAULT 0.00,
  `remaining_interest` DECIMAL(15,2) DEFAULT 0.00,
  `remaining_principal` DECIMAL(15,2) DEFAULT 0.00,
  `payment_date` DATE DEFAULT NULL,
  `dpd` INT DEFAULT 0,
  `remaining_amount` DECIMAL(15,2) DEFAULT 0.00,
  `extra_paid` DECIMAL(15,2) DEFAULT 0.00,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_rps_carepay_lan_due` (`lan`, `due_date`),
  KEY `idx_rps_carepay_status_due` (`status`, `due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
